# Generated by Django 4.0.3 on 2022-03-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_book_book_tracking_book_unique_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='feautred',
            new_name='featured',
        ),
    ]
