# Generated by Django 4.0.3 on 2022-03-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_rename_feautred_book_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book_tracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_user_tracking', to=settings.AUTH_USER_MODEL),
        ),
    ]
