# Generated by Django 4.0.3 on 2022-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0007_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
