# Generated by Django 4.0.3 on 2022-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0009_alter_book_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_tracking',
            name='status',
            field=models.CharField(choices=[('Want To Read', 'Want To Read'), ('Reading', 'Reading'), ('Read/Done', 'Read/Done')], max_length=200),
        ),
    ]
